### ISSUE TITLE
DRM minui patch isn't here

### ISSUE THREAD

**Issue by MLXProjects** [twaik/AROMA-tools#1]
I'd see that you had a fork (which doesn't exist anymore) with minui almost integrated, can you share it please?? 
I'm working on libaroma to support drm

**Comment by twaik** [comment]
I did not have it. Minui is recovery's ui solution and has nothing to do with libaroma.
The only way to make libaroma show content on screen is to kill recovery using `setprop ctl.stop recovery`. Sending "STOP" signal (what aroma does now) does not work because recovery process still has master connection to drm. After killing it you will be able to create new master connection. Remember that you should restart recovery (`setprop ctl.start recovery`) before exit from your program.

**Comment by MLXProjects** [comment]
> The only way to make libaroma show content on screen is to kill recovery using `setprop ctl.stop recovery`. Sending "STOP" signal (what aroma does now) does not work because recovery process still has master connection to drm. After killing it you will be able to create new master connection. Remember that you should restart recovery (`setprop ctl.start recovery`) before exit from your program.

Nope, libaroma doesn't support DRM so it can't init a framebuffer (just like aroma installer). 
> I did not have it. Minui is recovery's ui solution and has nothing to do with libaroma.

Why do you say that you didn't have it, if @CaptainThrowback has a branch called twaik [with all your updates](https://github.com/CaptainThrowback/AROMA-Installer/tree/twaik)? 

I've already learn that recovery needs to be stopped because of the drm master thing, and even after doing that it doesnt find a framebuffer (as said before, it has no drm support). 

Can you help on this? If not, I understand.

**Comment by twaik** [comment]
I do not think CaptainThrowback has something else than what I proposed you. I did not do anything like that. 
Everything I can say is that you can make custom libaroma frsmebuffer implementation which writes data directly to DRM. Minui is not something that can be integrated to libaroma, but you can use it's code to implement what you need.

**Comment by MLXProjects** [comment]
And then why did you get a minui surface and drawn to it's data buffer? 
That's how minui was implemented in your aroma installer fork
You don't seem going to help on this, sad because you actually have the ability and would be pretty useful (right now I'm able to write to drm screen, pretty glitched but works).

**Comment by twaik** [comment]
I tell you I do not remember if I did it. Maybe I did it a long time ago for someone I do not remember.
It was 2.5 years ago, I have already abandoned the project more than three times.
If you want to check if it works just buildit on top of your LineageOS build, but make sure minui is built with DRM as main backend. Then try to start it using adb like that:
```
adb push <path to AROMA Installer's update-binary> /update-binary
adb push <path to AROMA Installer's update.zip> /update.zip
adb shell setprop ctl.stop recovery
adb shell /update-binary 1 1 /update.zip
```
If it works insert [here](https://github.com/CaptainThrowback/AROMA-Installer/blob/twaik/src/main/aroma.c#L172) that line 

`system("setprop ctl.stop recovery");`

It should do exactly what you need.
